# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:09
from __future__ import unicode_literals

import os
import json

from django.db import migrations, models


def init_locales(apps, schema_editor):
    base_dir = os.path.dirname(os.path.abspath(__file__))
    locale_cls = apps.get_model('sxtr', 'Locales')
    for locale in json.load(open(os.path.join(base_dir, 'locales.json'), 'r')):
        locale_cls(**locale).save()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('locale', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locales',
            unique_together=set([('name', 'locale')]),
        ),
        migrations.RunPython(init_locales),
    ]
