# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sxtr', '0003_translatable_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='locales',
            options={'ordering': ('locale',)},
        ),
        migrations.AlterUniqueTogether(
            name='translations',
            unique_together=set([('application', 'locale')]),
        ),
    ]
