# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sxtr', '0004_auto_20160413_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ('name',), 'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelOptions(
            name='locales',
            options={'ordering': ('locale',), 'verbose_name': 'locale', 'verbose_name_plural': 'locales'},
        ),
        migrations.AlterModelOptions(
            name='translations',
            options={'permissions': (('edit_tr', 'Edit Translation'),), 'verbose_name': 'translation', 'verbose_name_plural': 'translations'},
        ),
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together=set([('name', 'abbreviation')]),
        ),
    ]
